import {City} from './city.js';
import {Address} from './address.js';

export class Journey {
  id: any;
  code: any;
  description!: string;
  subTitle!: string;
  journeyFiles: any[] = [];
  journeyType: any[] = [];
  journeyPeople: any[] = [];
  startDate: any;
  currentLabel!: string;
  status!: string;
  isRented!: string;
  published!: string;
  occupied: any;
  nonOccupiedFrom: any;
  condoName!: string;
  showAddress: any;
  privativeArea: any;
  deliverDate: any;
  buildingInProgress: any;
  city!: City;
  memo!: string;
  address: Address = new Address();
  apartmentNumber: any;
  landLength: any;
  totalLength: any;
  frontLength: any;
  sideLength: any;
  buildingLength: any;
  minValue: any;
  maxValue: any;
  condominium: any;
  parking: any;
  bedroom: any;
  bathroom: any;
  livingRoom: any;
  kitchen: any;
  suite: any;
  taxes: any;
  streetName: any;
  streetNumber: any;
  addressAdditional: any;
  neighborhood: any;
  operationType: any;
  journeyFunnel: any;
  html!: string;
  highlight: any;
  styleIcon: any;
  styleColor: any;
  selectedJourneyType: any[] = [];
  selectedAddressNeighborhood: any[] = [];
}
