export enum RoleType {
  ADMIN = 'ADMIN',
  ADMIN_PORTAL = 'ADMIN_PORTAL',
  ADMIN_REAL_ESTATE = 'ADMIN_REAL_ESTATE',
  ADMIN_TENANT = 'ADMIN_TENANT',
  ADMIN_ENCYCLOPEDIA = 'ADMIN_ENCYCLOPEDIA',
  ADMIN_FINANCE = 'ADMIN_FINANCE',
  EDITOR = 'EDITOR',
  ADMIN_JOURNEY = 'ADMIN_JOURNEY',
  EXTERNAL_USER = 'EXTERNAL_USER',  
}
